services:
  banner_api:
    build: .
    container_name: banner_api
    ports:
      - "80:80"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - drive: nvidia
              count: all
              capabilities: [gpu]
